sudo: false
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - libzmq-dev
    - libgmp-dev
    - libunistring-dev
    - libgc-dev
    - texinfo
    - lcov
cache:
  directories:
  - guile
  - guile-2.0.11
before_install:
  - sh ./utilities/get_guile.sh
  - export PKG_CONFIG_PATH=`pwd`/guile/lib/pkgconfig
  - export LD_LIBRARY_PATH=`pwd`/guile/lib:$LD_LIBRARY_PATH
  - export PATH=`pwd`/guile/bin:$PATH
  - gem install coveralls-lcov
script:
  - ./autogen.sh
  - CFLAGS="-fprofile-arcs -ftest-coverage" LDFLAGS="-lgcov" ./configure --prefix=`pwd`/guile
  - make
  - make install
  - guile -e main examples/hello-srv.scm &
  - guile -e main examples/hello-client.scm
after_success:
  - lcov -d examples -d . -base-directory . -c -o coverage.info
  - coveralls-lcov coverage.info
