sudo: false
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - libzmq-dev
    - libgmp-dev
    - libunistring-dev
    - libgc-dev
    - texinfo
cache:
  directories:
  - guile
  - guile-2.0.11
before_install:
  - sh ./utilities/get_guile.sh
  - export PKG_CONFIG_PATH=`pwd`/guile/lib/pkgconfig
  - export LD_LIBRARY_PATH=`pwd`/guile/lib:$LD_LIBRARY_PATH
  - export PATH=`pwd`/guile/bin:$PATH
script:
  - ./autogen.sh
  - ./configure --prefix=`pwd`/guile/site/2.0
  - make
  - make install
  - guile -e main examples/hello-srv.scm &
  - guile -e main examples/hello-client.scm

